apiVersion: v1
kind: Namespace
metadata:
  name: postgres

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
  namespace: postgres
subsets:
  - addresses:
      - ip: [PRIVATE_IP_OF_DROPLET]
    ports:
      - port: 5432
      - name: droplet